services:
  web:
    build: ./softkraft_recruitment
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./softkraft_recruitment:/opt/app
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.18
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
